### ISSUE TITLE
CHS.from_function and .from_data give an inconsistend API

### ISSUE THREAD

**Issue by mwappner** [neurophysik/CHSPy#3]
When messing around with [this example](https://github.com/neurophysik/jitcdde/blob/master/examples/data_input.py) and replacing the `ChubicHermiteSpline.from_data` call with a corresponding `from_function` call I was initially confused by the error messages, since I wasn't expecting the former to be a class method and the latter to be an instance method. Upon reading the documentation, that became clearer and I understood that I had to do
```
my_spline = CubicHermiteSpline(n=2)
my_spline.from_function(my_function, times)
```
but that begs the question: shouldn't this function be a class method to build splines from the ground up? I'm assuming the function was added with something in mind that doesn't align with this idea, and modifying it now would harm backwards compatibility. Regardless I think it might be worth sparing thought for making the API more uniform and making `from_function` a class method by making it detect the dimension of the spline, like `from_data`, or by adding an extra argument `n` to the method. I'd be willing to PR a draft if you don't feel you have the time to do it now, but also would like to see this implemented.

**Comment by Wrzlprmft** [comment]
> shouldn't this function be a class method to build splines from the ground up? I'm assuming the function was added with something in mind that doesn't align with this idea, and modifying it now would harm backwards compatibility.

Exactly. It’s historic baggage.

> Regardless I think it might be worth sparing thought for making the API more uniform and making `from_function` a class method by making it detect the dimension of the spline, like `from_data`, or by adding an extra argument `n` to the method.

I added a class method `from_func`, which works as you would expect. I left `from_function` for the aforementioned backwards compatibility.

**Comment by mwappner** [comment]
Wouldn't `n = len(function(test_time))` consume a step of an iterator, if `function` is an iterator? I think it's a reasobale thing to do, but issuing a warning might be worth it?

Other than that, this is nice. It'd be awsome to get a release at some point so jitcdde installs the latest CHSPy.

**Comment by Wrzlprmft** [comment]
> Wouldn't `n = len(function(test_time))` consume a step of an iterator, if `function` is an iterator? I think it's a reasobale thing to do, but issuing a warning might be worth it?

If `function(test_time)` is a consumable iterator (e.g., because `function` is a generator function), you get an error because it has no length. I didn’t specify so far what exactly `function` should return, but I now say that it should be an iterable (which is not the same as an iterator). I don’t see why somebody would use a consumable iterator here and if somebody does, they get an error message, that is hopefully sufficiently clear. Thus, I am fine with this.
 
> Other than that, this is nice. It'd be awsome to get a release at some point so jitcdde installs the latest CHSPy.

Sure. Let me just wait for a few days so you can find any bugs that I created.
